---
- name: Install packages dependencies
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - perl-libwww-perl
    - perl-Crypt-SSLeay
    - perl-LWP-Protocol-https
  tags:
    - slack_nagios

- name: Download slack plugin
  get_url:
    url: "{{ slack_nagios_url }}/nagios.pl"
    dest: "{{ slack_nagios_bindir }}/slack_nagios.pl"
    mode: 0755
  tags:
    - slack_nagios
    - slack_nagios-plugin

- name: Update slack domain workspace
  lineinfile:
    path: "{{ slack_nagios_bindir }}/slack_nagios.pl"
    regexp: '^my \$opt_domain ='
    line: 'my $opt_domain = "{{ slack_nagios_domain }}";'
  tags:
    - slack_nagios
    - slack_nagios-creds

- name: Update slack token
  lineinfile:
    path: '{{ slack_nagios_bindir }}/slack_nagios.pl'
    regexp: '^my \$opt_token ='
    line: 'my $opt_token = "{{ slack_nagios_token }}";'
  tags:
    - slack_nagios
    - slack_nagios-creds

- name: Deploy Slack commands
  template:
    src: nagios-command.cfg.j2
    dest: '{{ slack_nagios_command_incdir }}/slack.cfg'
    owner: 'root'
    group: 'root'
  tags:
    - slack_nagios
    - slack_nagios-command
